### ISSUE TITLE
Not fully working

### ISSUE THREAD

**Issue by MrGung** [SalvatoreTosti/saltosti.com#1]
See tweets: https://twitter.com/borkdude/status/1484910075751931905?t=jLkDVsowwv_0ezIrJHPlzg&s=19

**Comment by SalvatoreTosti** [comment]
Thanks for submitting an issue about this thread.
Images should be fixed, I'll look into the HTTP / HTTPS fallback. 👍

**Comment by SalvatoreTosti** [comment]
HTTPS should now be used by default.
Thanks again for creating this issue @MrGung!
